# Generated by Django 4.1.3 on 2022-12-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('type1', models.CharField(max_length=20)),
                ('type2', models.CharField(blank=True, max_length=20, null=True)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
