# Generated by Django 4.1.3 on 2022-12-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_pokemon_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='image_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
