# Generated by Django 4.1.3 on 2022-12-05 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_pokemon_height_alter_pokemon_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='image',
        ),
    ]
